package com.example.sudoku.model

import android.widget.Button
import com.example.sudoku.databinding.ActivityMainBinding

class Buttons {
    lateinit var binding: ActivityMainBinding
    fun returnButton(): List<Button> {
        val buttonList = arrayListOf<Button>(
            binding.b11,
            binding.b12,
            binding.b13,
            binding.b21,
            binding.b22,
            binding.b23,
            binding.b31,
            binding.b32,
            binding.b33,
            binding.b14,
            binding.b15,
            binding.b16,
            binding.b24,
            binding.b25,
            binding.b26,
            binding.b34,
            binding.b35,
            binding.b36,
            binding.b17,
            binding.b18,
            binding.b19,
            binding.b27,
            binding.b28,
            binding.b29,
            binding.b37,
            binding.b38,
            binding.b39,

            binding.b41,
            binding.b42,
            binding.b43,
            binding.b51,
            binding.b52,
            binding.b53,
            binding.b61,
            binding.b62,
            binding.b63,
            binding.b44,
            binding.b45,
            binding.b46,
            binding.b54,
            binding.b55,
            binding.b56,
            binding.b64,
            binding.b65,
            binding.b66,
            binding.b47,
            binding.b48,
            binding.b49,
            binding.b57,
            binding.b58,
            binding.b59,
            binding.b67,
            binding.b68,
            binding.b69,

            binding.b71,
            binding.b72,
            binding.b73,
            binding.b81,
            binding.b82,
            binding.b83,
            binding.b91,
            binding.b92,
            binding.b93,
            binding.b74,
            binding.b75,
            binding.b76,
            binding.b84,
            binding.b85,
            binding.b86,
            binding.b94,
            binding.b95,
            binding.b96,
            binding.b77,
            binding.b78,
            binding.b79,
            binding.b87,
            binding.b88,
            binding.b89,
            binding.b97,
            binding.b98,
            binding.b99,
        )
        return buttonList
    }
}